"""crear_estructura_core_y_auditoria

Revision ID: 0a72753bfb90
Revises: 
Create Date: 2026-05-19 19:41:51.558868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a72753bfb90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_universitario', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.CheckConstraint("rol IN ('ESTUDIANTE', 'PROFESOR', 'ADMIN')", name='check_rol_valido'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('codigo_universitario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('cursos',
    sa.Column('id_curso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_curso', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('gestion', sa.String(length=10), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_profesor'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curso'),
    sa.UniqueConstraint('codigo_curso')
    )
    op.create_table('curso_estudiante',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_curso', 'id_estudiante')
    )
    op.create_table('tareas',
    sa.Column('id_tarea', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ),
    sa.PrimaryKeyConstraint('id_tarea')
    )
    op.create_table('criterios_calificacion',
    sa.Column('id_criterio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('ponderacion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id_tarea'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_criterio')
    )
    op.create_table('intentos',
    sa.Column('id_intento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('numero_intento', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('url_codigo_fuente', sa.String(length=255), nullable=False),
    sa.Column('nota_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('ENVIADO', 'PROCESANDO', 'CALIFICADO', 'RECHAZADO')", name='check_estado_valido'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id_tarea'], ),
    sa.PrimaryKeyConstraint('id_intento')
    )
    op.create_table('calificaciones_por_criterio',
    sa.Column('id_intento', sa.Integer(), nullable=False),
    sa.Column('id_criterio', sa.Integer(), nullable=False),
    sa.Column('nota_obtenida', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_criterio'], ['criterios_calificacion.id_criterio'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_intento'], ['intentos.id_intento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_intento', 'id_criterio')
    )
    op.create_table('historial_auditoria',
    sa.Column('id_auditoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_intento', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('valor_anterior', sa.JSON(), nullable=True),
    sa.Column('valor_nuevo', sa.JSON(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ejecutado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ejecutado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_intento'], ['intentos.id_intento'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_auditoria')
    op.drop_table('calificaciones_por_criterio')
    op.drop_table('intentos')
    op.drop_table('criterios_calificacion')
    op.drop_table('tareas')
    op.drop_table('curso_estudiante')
    op.drop_table('cursos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
