"""crear_estructura_core_y_auditoria2

Revision ID: c2b0f9da5523
Revises: df19518c157b
Create Date: 2026-05-19 20:52:11.174930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b0f9da5523'
down_revision: Union[str, None] = 'df19518c157b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intentos', sa.Column('contenido_codigo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intentos', 'contenido_codigo')
    # ### end Alembic commands ###
