"""crear_estructura_core_y_auditoria2

Revision ID: df19518c157b
Revises: 0a72753bfb90
Create Date: 2026-05-19 20:37:56.827790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df19518c157b'
down_revision: Union[str, None] = '0a72753bfb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriculas',
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_matricula')
    )
    op.create_index(op.f('ix_matriculas_id_matricula'), 'matriculas', ['id_matricula'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matriculas_id_matricula'), table_name='matriculas')
    op.drop_table('matriculas')
    # ### end Alembic commands ###
